on: [push, pull_request]

name: build-binary

jobs:
  build-windows:
    strategy:
      matrix:
        target: [x86_64-pc-windows-msvc]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: build
          args: --release --target ${{ matrix.target }}
      - uses: actions/upload-artifact@v2
        with:
          name: build-windows
          path: ./target/${{ matrix.target }}/release/trojan-rust.exe
      - uses: svenstaro/upload-release-action@v1-release
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./target/${{ matrix.target }}/release/trojan-rust.exe
          asset_name: trojan-rust-${{ matrix.target }}.exe
          tag: ${{ github.ref }}

  build-linux:
    strategy:
      matrix:
        target: [x86_64-unknown-linux-musl, aarch64-unknown-linux-musl]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          toolchain: nightly
          command: build
          args: --release --target ${{ matrix.target }}
      - uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.target }}
          path: ./target/${{ matrix.target }}/release/trojan-rust
      - uses: svenstaro/upload-release-action@v1-release
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./target/${{ matrix.target }}/release/trojan-rust
          asset_name: trojan-rust-${{ matrix.target }}
          tag: ${{ github.ref }}
